CREATE TABLE usuarios
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome             VARCHAR(150) NOT NULL,
    email            VARCHAR(170) NOT NULL,
    telefone         VARCHAR(14)  NOT NULL,
    cpf              VARCHAR(14)  NOT NULL,
    senha            VARCHAR(100) NOT NULL,
    data_nascimento  DATE         NOT NULL,
    data_criacao     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP,

--     constraints declaradas separadamente para melhor legibilidade, escolher um nome bom e organização (topo: define quais dados (nomes e tipos) - fundo: define regras de negócio)
--     exemplo: se precisar remover essa regra futuramente (ALTER TABLE usuarios DROP CONSTRAINT uk_usuarios_email)
--     exemṕlo: se o banco gerar um log de erro, irá aparecer o nome "bonitinho" da constraint facilitando diagnóstico
    CONSTRAINT pk_usuarios
        PRIMARY KEY (id),

    CONSTRAINT uk_usuarios_email
        UNIQUE (email),

    CONSTRAINT uk_usuarios_cpf
        UNIQUE (cpf)
);