-- Habilita a extensão para geração de UUIDs no PostgreSQL (caso queira gerar via BD)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- TABELA: usuarios
-- =============================================================================
CREATE TABLE usuarios
(
    id               UUID                        NOT NULL,
    nome             VARCHAR(150)                NOT NULL,
    email            VARCHAR(255)                NOT NULL,
    telefone         VARCHAR(255)                NOT NULL,
    cpf              VARCHAR(255)                NOT NULL,
    senha            VARCHAR(100)                NOT NULL,
    data_nascimento  DATE                        NOT NULL,
    excluido         BOOLEAN                     NOT NULL DEFAULT FALSE,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_cpf UNIQUE (cpf)
);

-- =============================================================================
-- TABELA: carteira
-- =============================================================================
CREATE TABLE carteira
(
    id           UUID                        NOT NULL,
    nome         VARCHAR(50)                 NOT NULL,
    saldo        NUMERIC(19, 2)              NOT NULL,
    data_criacao TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    usuario_id   UUID,
    versao       BIGINT,

    CONSTRAINT pk_carteira PRIMARY KEY (id),

    CONSTRAINT uk_carteira_usuario UNIQUE (usuario_id),

    CONSTRAINT fk_carteira_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id) ON DELETE CASCADE
);

-- =============================================================================
-- TABELA: transacoes
-- =============================================================================
CREATE TABLE transacoes
(
    id                  UUID                        NOT NULL,
    valor               NUMERIC(19, 2)              NOT NULL,
    tipo_transacao      VARCHAR(255)                NOT NULL,
    carteira_origem_id  UUID,
    carteira_destino_id UUID,
    data_criacao        TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pk_transacoes PRIMARY KEY (id),

    CONSTRAINT fk_transacoes_carteira_origem FOREIGN KEY (carteira_origem_id)
        REFERENCES carteira (id),

    CONSTRAINT fk_transacoes_carteira_destino FOREIGN KEY (carteira_destino_id)
        REFERENCES carteira (id)
);

-- Índices para melhorar a performance de buscas em transações
CREATE INDEX idx_transacoes_carteira_origem ON transacoes (carteira_origem_id);
CREATE INDEX idx_transacoes_carteira_destino ON transacoes (carteira_destino_id);


-- CREATE TABLE usuarios
-- (
-- --     id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
-- --     id               UUID DEFAULT gen_random_uuid(),
--     id               UUID,
--     nome             VARCHAR(150) NOT NULL,
--     email            VARCHAR(170) NOT NULL,
--     telefone         VARCHAR(14)  NOT NULL,
--     cpf              VARCHAR(14)  NOT NULL,
--     senha            VARCHAR(100) NOT NULL,
--     data_nascimento  DATE         NOT NULL,
--     excluido         BOOLEAN      NOT NULL DEFAULT FALSE,
--     data_criacao     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     data_atualizacao TIMESTAMP,
--
-- --     constraints declaradas separadamente para melhor legibilidade, escolher um nome bom e organização (topo: define quais dados (nomes e tipos) - fundo: define regras de negócio)
-- --     exemplo: se precisar remover essa regra futuramente (ALTER TABLE usuarios DROP CONSTRAINT uk_usuarios_email)
-- --     exemṕlo: se o banco gerar um log de erro, irá aparecer o nome "bonitinho" da constraint facilitando diagnóstico
--     CONSTRAINT pk_usuarios
--         PRIMARY KEY (id),
--
--     CONSTRAINT uk_usuarios_email
--         UNIQUE (email),
--
--     CONSTRAINT uk_usuarios_cpf
--         UNIQUE (cpf)
-- );
--
--
-- -- ALTER TABLE usuarios
-- --     ADD COLUMN excluido BOOLEAN NOT NULL DEFAULT FALSE;