-- -- 1. Garante a função geradora de UUID
-- --    (nativa no PostgreSQL 13+; para versões antigas use "uuid-ossp" no lugar)
-- CREATE EXTENSION IF NOT EXISTS "pgcrypto";
--
-- -- 2. Remove o comportamento de identidade da coluna
-- ALTER TABLE usuarios
--     ALTER COLUMN id DROP IDENTITY;
--
-- -- 3. Converte o tipo de BIGINT para UUID
-- --    O USING gera um UUID aleatório para cada linha existente
-- ALTER TABLE usuarios
--     ALTER COLUMN id TYPE UUID USING (gen_random_uuid());
--
-- -- 4. (Opcional) valor padrão para inserts que não informem o id
-- ALTER TABLE usuarios
--     ALTER COLUMN id SET DEFAULT gen_random_uuid();